### ISSUE TITLE
TypeError: Cannot read property 'destroyed' of null

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd-nodejs-server#19]
```
TypeError: Cannot read property 'destroyed' of null
    at _respond (/node_modules/cometd-nodejs-server/cometd-nodejs-server.js:266:44)
    at /node_modules/cometd-nodejs-server/cometd-nodejs-server.js:551:21
    at _asyncFoldLeft (/node_modules/cometd-nodejs-server/cometd-nodejs-server.js:75:9)
    at _next (/node_modules/cometd-nodejs-server/cometd-nodejs-server.js:72:13)
    at _process (/node_modules/cometd-nodejs-server/cometd-nodejs-server.js:566:13)
    at _processMessages (/node_modules/cometd-nodejs-server/cometd-nodejs-server.js:492:13)
```

**Comment by sbordet** [comment]
This may happen similarly to #9 if the client destroys the connection before the server has the chance to reply.
